name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 0 0 * * *

jobs:
  template:
    runs-on: ubuntu-latest
    needs:
    environment:
      emacs:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: labs.phundrak.com
          username: ${{ gitea.actor }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set environment
        shell: bash
        run: |
          yq() { docker run --rm -i -v "${PWD}":/workdir mikefarah/yq "$@"; }
          VERSION=${{ env.emacs }}
          tags=$(yq ".[] | select(.tags[0] == \"$VERSION\") | .tags | join (\", phundrak/emacs:\")" images.yml)
          version=$(yq ".[] | select(.tags[0] == \"$VERSION\") | .version" images.yml)
          cache=$(yq ".[] | select(.tags[0] == \"$VERSION\") | .tags[0]" images.yml)
          template=$(yq ".[] | select(.tags[0] == \"$VERSION\") | .template" images.yml)
          echo "image_tags=phundrak/emacs:$tags" >> $GITEA_ENV
          echo "image_cache=phundrak/emacs:$cache" >> $GITEA_ENV
          echo "image_context=$version/$template" >> $GITEA_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: ${{ gitea.ref == 'refs/heads/master' }}
          tags: ${{ env.image_tags }}
          context: ${{ env.image_context }}
